import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {ChangeEvent, SetStateAction, SyntheticEvent, useState} from "react";

const inter = Inter({subsets: ['latin']})

export default function Home() {

    const [data, setData] = useState({
        name: '',
        password: '',
        password2: '',
        profession: ''
    })

    const [agree, setAgree] = useState(false)

    const handleChange = (event: ChangeEvent<HTMLInputElement> | ChangeEvent<HTMLSelectElement>) => {
        const {name, value} = event.target
        setData({...data, [name]: value})
    }

    const handleAgree = (event: ChangeEvent<HTMLInputElement>) => {
        setAgree(event.target.checked)
    }

    const handleSubmit = (event: SyntheticEvent) => {
        event.preventDefault()
        alert(`Uživatel ${data.name} je ${data.profession} developer. Jeho heslo je ${data.password2}`)
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
            <h1>Form</h1>
          <form onSubmit={handleSubmit}>
              <div>
                  <label>
                      Name:
                      <input id="name" name="name" type="text" value={data.name} onChange={handleChange}/>
                  </label>
              </div>
              <div>
                  <label>
                      Password:
                      <input id="password" name="password" type="password" value={data.password} onChange={handleChange}/>
                  </label>
              </div>
              <div>
                  <label>
                      Password 2:
                      <input id="password2" name="password2" type="password" value={data.password2} onChange={handleChange}/>
                  </label>
              </div>
              <div>
                  <label>
                      Profession:
                      <select id="profession" name="profession" value={data.profession} onChange={handleChange}>
                          <option value="frontend">Frontend</option>
                          <option value="backend">Backend</option>
                      </select>
                  </label>
              </div>
              <div>
                  <label>
                      Souhlasím s podmínkami:
                      <input id="agree" name="agree" type="checkbox" onChange={handleAgree}/>
                  </label>
              </div>
              <div>
                  <button disabled={!agree || data.password !== data.password2} type="submit">Submit</button>
              </div>
          </form>
      </main>
    </>
  )
}
