import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {ChangeEvent, SetStateAction, useState} from "react";

const inter = Inter({subsets: ['latin']})

export default function Home() {

    const [name, setName] = useState('')
    const [password, setPassword] = useState('')
    const [password2, setPassword2] = useState('')
    const [profession, setProfession] = useState('')
    const [agree, setAgree] = useState(false)

    const handleName = (event: ChangeEvent<HTMLInputElement>) => {
        setName(event.target.value)
    }

    const handlePassword = (event: ChangeEvent<HTMLInputElement>) => {
        setPassword(event.target.value)
    }

    const handlePassword2 = (event: ChangeEvent<HTMLInputElement>) => {
        setPassword2(event.target.value)
    }

    const handleProfession = (event: ChangeEvent<HTMLInputElement>) => {
        setProfession(event.target.value)
    }

    const handleAgree = (event: ChangeEvent<HTMLInputElement>) => {
        setAgree(event.target.checked)
    }

    const handleSubmit = (event: Event) => {
        event.preventDefault()
        alert(`Uživatel ${name} je ${profession} developer. Jeho heslo je ${password}`)
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
            <h1>Form</h1>
          <form onSubmit={handleSubmit}>
              <div>
                  <label>
                      Name:
                      <input id="name" type="text" value={name} onChange={handleName}/>
                  </label>
              </div>
              <div>
                  <label>
                      Password:
                      <input id="password" type="password" value={password} onChange={handlePassword}/>
                  </label>
              </div>
              <div>
                  <label>
                      Password 2:
                      <input id="password2" type="password" value={password2} onChange={handlePassword2}/>
                  </label>
              </div>
              <div>
                  <label>
                      Profession:
                      <select id="profession" value={profession} onChange={handleProfession}>
                          <option value="frontend">Frontend</option>
                          <option value="backend">Backend</option>
                      </select>
                  </label>
              </div>
              <div>
                  <label>
                      Souhlasím s podmínkami:
                      <input id="agree" type="checkbox" onChange={handleAgree}/>
                  </label>
              </div>
              <div>
                  <button disabled={!agree || password !== password2} type="submit">Submit</button>
              </div>
          </form>
      </main>
    </>
  )
}
